version: '3'

services:
  smart-backend:
    container_name: smart-backend
    image: smart-backend:v1
    ports:
      - "8082:8081"
    environment:
      - APP_ENV=prod
    volumes:
      - ./config/prod.yaml:/app/config/prod.yaml
    networks:
      - smart-net

  smart-frontend:
    container_name: smart-frontend
    image: smart-frontend:v1
    ports:
      - "81:81"
    volumes:
      - ./nginx.prod.conf:/etc/nginx/conf.d/default.conf # 这里的 nginx.prod.conf 我们稍后创建
    networks:
      - smart-net
    depends_on:
      - smart-backend

networks:
  smart-net:
    driver: bridge
