events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    server {
        listen       90;
        server_name  localhost;

        # 1. 前端页面 (指向容器内的 /html 目录)
        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
            try_files $uri $uri/ /index.html; # 防止 Vue 刷新 404
        }

        # 2. 后端接口代理 (转发给 Go 容器)
        location /api/ {
            proxy_pass http://app:8080/api/; # 'app' 是 docker-compose 里的服务名
            proxy_set_header Host $host;
        }
    }
}