db:
  # 线上数据库地址 (如果后端和数据库在同一台机器，建议用 127.0.0.1 避免防火墙问题)
  dsn: "root:123456@tcp(127.0.0.1:3306)/smart_community?charset=utf8mb4&parseTime=True&loc=Local"

redis:
  # 线上 Redis 地址
  addr: "127.0.0.1:6359"

minio:
  endpoint: "43.138.85.114:9000"           # 必须用公网 IP，否则前端无法访问图片
  access_key: "minioadmin"
  secret_key: "minioadmin123"
  bucket: "community"
  use_ssl: false